version: "3.9"

services:
  db:
    image: postgres:15
    container_name: test_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: test_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/testdb?sslmode=disable"
    ports:
      - "8080:8080"

volumes:
  pgdata: